<a href="https://colab.research.google.com/github/racaio/Python_Pandas_Sql/blob/main/PythonSql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import sqlalchemy

In [48]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text
# create_engine = motor que fara meu banco de dados rodar // Medatada = CLasso do banco de dados

In [46]:
banco_dados = create_engine('sqlite:///memory:')
#sqllite, ja ve instalado // Memory informa que esotu usando memoria local.

In [22]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

In [23]:
import pandas as pd

In [24]:
dados = pd.read_csv(url) #Leitura do CSV
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [39]:
#dados.to_sql('clientes', banco_dados, index = False) # nome do banco, motor de criação

In [29]:
var_inspector = inspect(banco_dados)#verificação do banco de dados

In [30]:
print(var_inspector.get_table_names()) # printa a tabela

['clientes', 'empregado']

In [31]:
# consultas SQl dentro da Tabela

In [32]:
var_query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'
empregados = pd.read_sql(var_query, banco_dados) # junto o motor do banco de dados.
empregados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio

In [34]:
#empregados.to_sql('empregado', con=banco_dados) #junto ao con+ motor assim savei essa nova tabela

In [35]:
pd.read_sql_table('empregado', banco_dados)# lendo a nova tabela completa

,index,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,2,5008812,61,Ensino superior,Divorciado,1,Pensionista,Outro,0,283500.0,0,Casa/apartamento próprio
3,3,5008813,61,Ensino superior,Divorciado,1,Pensionista,Outro,0,283500.0,0,Casa/apartamento próprio
4,4,5008814,61,Ensino superior,Divorciado,1,Pensionista,Outro,0,283500.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...,...
117494,117494,6837198,56,Ensino superior,Divorciado,1,Pensionista,Outro,0,211500.0,0,Casa/apartamento próprio
117495,117495,6837264,43,Ensino superior,Solteiro,4,Servidor público,Equipe principal,3,90000.0,0,Casa/apartamento próprio
117496,117496,6837707,36,Ensino superior,União-estável,2,Empregado,Construção Civil,6,202500.0,0,Casa/apartamento próprio
117497,117497,6839917,30,Ensino superior,Casado,2,Pensionista,Outro,7,180000.0,0,Casa/apartamento próprio
117498,117498,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais

In [51]:
pd.read_sql_table('empregado', banco_dados, columns=['ID_Cliente','Grau_escolaridade','Categoria_de_renda'])#com algumas colunas especificas

        ID_Cliente Grau_escolaridade   Categoria_de_renda
0          5008804   Ensino superior            Empregado
1          5008805   Ensino superior            Empregado
2          5008812   Ensino superior          Pensionista
3          5008813   Ensino superior          Pensionista
4          5008814   Ensino superior          Pensionista
...            ...               ...                  ...
117494     6837198   Ensino superior          Pensionista
117495     6837264   Ensino superior     Servidor público
117496     6837707   Ensino superior            Empregado
117497     6839917   Ensino superior          Pensionista
117498     6841878   Ensino superior  Associado comercial

[117499 rows x 3 columns]

In [37]:
# Atualizando bando de dados.

In [50]:
query = '  DELETE FROM clientes WHERE ID_Cliente = 5008804'
with banco_dados.connect() as conn:
  conn.execute(text(query))
  conn.commit()
  # delete realizado

In [58]:
pd.read_sql_table('clientes', banco_dados)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino superior,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [57]:
query = 'UPDATE Clientes SET Grau_escolaridade = "Ensino superior" WHERE ID_Cliente = 5008806'
with banco_dados.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [59]:
pd.read_sql_table('clientes', banco_dados)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino superior,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio